@startuml drivetrain

class Drivetrain
class Navigator
class ServoController
class ParallexFeedback360
class AdafruitNXP9DOF
class SlamtecA1RPLiDaR

class UART
class SPI
class I2C

interface INetworkManager
interface INavigator
interface IMotorController
interface IServo
interface IMagnometer
interface IAccerelometer
interface IGyroscope
interface ILiDaR

Navigator .u.|> INavigator
ServoController .u.|> IMotorController
ParallexFeedback360 .u.|> IServo
AdafruitNXP9DOF .u.|> IMagnometer
AdafruitNXP9DOF .u.|> IAccerelometer
AdafruitNXP9DOF .u.|> IGyroscope
SlamtecA1RPLiDaR .u.|> ILiDaR
NetworkManager .u.|> INetworkManager

Drivetrain --* INavigator
Drivetrain --* INetworkManager

Navigator --* IMotorController
Navigator --* IMagnometer
Navigator --* IAccerelometer
Navigator --* IGyroscope
Navigator --* ILiDaR

ServoController --* IServo
ServoController --* IGyroscope

AdafruitNXP9DOF --> I2C

SlamtecA1RPLiDaR --> UART

NetworkManager --> SPI

@enduml